// HÄMTA ALLA ANVÄNDARE

GET http://localhost:3000/all-users


###


// SKAPA ANVÄNDARE
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Carina",
  "password": "test"
}

###


// LOGGA IN ANVÄNDARE // VID FEL LÖSENORD SÅ SKALL SVARA MED 401
POST http://localhost:3000/login
Content-Type: application/json

{
  "name": "Helena",
  "password": "test"
}

###
